# Generated by Django 2.0.6 on 2019-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.IntegerField()),
                ('EmpName', models.CharField(max_length=30)),
                ('EmpSal', models.FloatField()),
                ('EmpAddr', models.CharField(max_length=30)),
            ],
        ),
    ]
